
```{r}
allData=read.csv("allData.csv")
```

Caminos

```{r}

stdData=grep("std$",names(allData),fixed = F)
decilData=grep("decil$",names(allData),fixed = F)
```

Camino STD
```{r}
dataClusStd=allData[,stdData]
rownames(dataClusStd)=allData$DepaProvDis
```

Distancias
```{r}
library(cluster)
set.seed(123)
distances=daisy(dataClusStd,metric = "euclidean")
```

Explorando cantidad a pedir
```{r}
library(factoextra)
set.seed(31)
fviz_nbclust(x = dataClusStd, 
             FUNcluster = pam, 
             diss=distances,
             method = "wss", 
             k.max = 10,
             verbose = F) 

# fviz_nbclust(x = dataClusStd, 
#              FUNcluster = hcut, 
#              diss=distances,
#              method = "wss", 
#              k.max = 10,
#              verbose = F,
#              hc_func = "agnes") 
# 
# fviz_nbclust(x = dataClusStd, 
#              FUNcluster = hcut, 
#              diss=distances,
#              method = "wss", 
#              k.max = 10,
#              verbose = F,
#              hc_func = "diana") 

# fviz_nbclust(dataClusStd, 
#              pam,
#              diss=distances,
#              method = "gap_stat",
#              k.max = 10,verbose = F)

# fviz_nbclust(dataclust, 
#              hcut,
#              diss=distances,
#              method = "gap_stat",
#              k.max = 10,
#              verbose = F,
#              hc_func = "agnes")

# fviz_nbclust(dataclust, 
#              hcut,
#              diss=distances,
#              method = "gap_stat",
#              k.max = 10,
#              verbose = F,
#              hc_func = "diana")
```


Calculando clusters

```{r}
NumberOfClusterDesired=10

res.pam = pam(x=distances,
              k = NumberOfClusterDesired,
              cluster.only = F)

res.agnes= hcut(distances, 
                k = NumberOfClusterDesired,
                isdiss=TRUE,
                hc_func='agnes',
                hc_method = "ward.D2")
res.diana= hcut(distances, 
                k = NumberOfClusterDesired,
                isdiss=TRUE,
                hc_func='diana',
                hc_method = "ward.D2")

allData$pamStd=as.factor(res.pam$clustering)
allData$agnStd=as.factor(res.agnes$cluster)
allData$diaStd=as.factor(res.diana$cluster)
```

Recodificando

```{r}
library(magrittr)
library(dplyr)
aggregate(data=allData,
          cbind(NBS_2017,NBS_2017_std)~pamStd,
          FUN=mean)%>%arrange(-NBS_2017)
```

```{r}
library(dplyr)

allData$pamStd=dplyr::recode_factor(allData$pamStd, 
                  `10` = '10',`1`='9',`5`='8',`7`='7',`4`='6',
                  `8` = '5',`6`='4',`9`='3',`2`='2',`3`='1')
allData$agnStd=dplyr::recode_factor(allData$agnStd, 
                  `10` = '10',`1`='9',`5`='8',`7`='7',`4`='6',
                  `8` = '5',`6`='4',`9`='3',`2`='2',`3`='1')
allData$diaStd=dplyr::recode_factor(allData$diaStd, 
                  `10` = '10',`1`='9',`5`='8',`7`='7',`4`='6',
                  `8` = '5',`6`='4',`9`='3',`2`='2',`3`='1')
```

Evaluando:

```{r}
fviz_silhouette(res.pam)
```
```{r}
fviz_silhouette(res.agnes)
```

```{r}
fviz_silhouette(res.diana)
```
Validando

```{r}
table(allData$Zona,allData$pamStd)
```

```{r}
table(allData$Zona,allData$agnStd)
```

```{r}
table(allData$Zona,allData$diaStd)
```


Camino DECIL
```{r}
dataClusDecil=allData[,decilData]
rownames(dataClusDecil)=allData$DepaProvDis
dataClusDecil[,]=lapply(dataClusDecil[,],as.ordered)
```

```{r}
library(cluster)
set.seed(123)
distancesDEC=daisy(dataClusDecil,metric = "gower")
hc <- hclust(distancesDEC, method = "ward.D2",)
plot(hc,labels=F)
```

```{r}

res.pam = pam(x=distancesDEC,
              k = NumberOfClusterDesired,
              cluster.only = F)

res.agnes= hcut(distancesDEC, 
                k = NumberOfClusterDesired,
                isdiss=TRUE,
                hc_func='agnes',
                hc_method = "ward.D2")
res.diana= hcut(distancesDEC, 
                k = NumberOfClusterDesired,
                isdiss=TRUE,
                hc_func='diana',
                hc_method = "ward.D2")

allData$pamDec=as.factor(res.pam$clustering)
allData$agnDec=as.factor(res.agnes$cluster)
allData$diaDec=as.factor(res.diana$cluster)
```


```{r}
aggregate(data=allData,
          cbind(NBS_2017,NBS_2017_decil)~pamDec,
          FUN=mean)%>%arrange(-NBS_2017)
```


```{r}
allData$pamDec=dplyr::recode_factor(allData$pamDec, 
                  `1` = '10',`9`='9',`5`='8',`10`='7',`7`='6',
                  `8` = '5',`6`='4',`3`='3',`4`='2',`2`='1')
allData$agnDec=dplyr::recode_factor(allData$agnDec, 
                  `1` = '10',`9`='9',`5`='8',`10`='7',`7`='6',
                  `8` = '5',`6`='4',`3`='3',`4`='2',`2`='1')
allData$diaDec=dplyr::recode_factor(allData$diaDec, 
                  `1` = '10',`9`='9',`5`='8',`10`='7',`7`='6',
                  `8` = '5',`6`='4',`3`='3',`4`='2',`2`='1')
```

Evaluando

```{r}
fviz_silhouette(res.pam)
```
```{r}
fviz_silhouette(res.agnes)
```

```{r}
fviz_silhouette(res.diana)
```
Validando

```{r}
table(allData$Zona,allData$pamDec)
```

```{r}
table(allData$Zona,allData$agnDec)
```

```{r}
table(allData$Zona,allData$diaDec)
```
```{r}
projectedData_std = cmdscale(distances, k=2)
projectedData_dec = cmdscale(distancesDEC, k=2)
allData$std1 = projectedData_std[,1]
allData$std2 = projectedData_std[,2]
allData$dec1 = projectedData_dec[,1]
allData$dec2 = projectedData_dec[,2]
```


```{r}
base= ggplot(data=allData,
             aes(x=std1, y=std2,
                 label=Distrito)) 
base + geom_text(size=0.5)
```


```{r}
base= ggplot(data=allData,
             aes(x=std1, y=std2,
                 color=Zona)) 
base + geom_point(alpha=0.5)
```


```{r}
base= ggplot(data=allData,
             aes(x=dec1, y=dec2,
                 color=pamStd)) 
base + geom_point(alpha=0.6)+facet_grid(~Zona)
```

```{r}
library("dbscan")
cl <- hdbscan(dataClusStd, minPts = 10)
allData$hd_clus=as.factor(cl$cluster)
allData$hd_clusprob=cl$membership_prob
allData$hd_clusout=cl$outlier_scores
```


```{r}
base= ggplot(data=allData,
             aes(x=std1, y=std2,
                 color=hd_clus)) 
base + geom_point(alpha=0.7) + facet_grid(~Zona)
```

```{r}
dataClusDecil[,]=lapply(dataClusDecil[,], as.integer)
cldec <- hdbscan(dataClusDecil, minPts = 10,xdist =distancesDEC )
allData$hd_clus_d=as.factor(cldec$cluster)
allData$hd_clusprob_d=cldec$membership_prob
allData$hd_clusout_d=cldec$outlier_scores
```

```{r}
base= ggplot(data=allData,
             aes(x=dec1, y=dec2,
                 color=hd_clus_d)) 
base + geom_point(alpha=0.7) + facet_grid(hd_clus_d~Zona)
```
```{r}
saveRDS(allData,"allData.rds")
#readRDS(file = "allData.rds")
```

